sudo: false 
 
language: 
 - java 11
 - java 10
 - java 9
 - java 8
 - java 7
 
services: 
 
- docker 
 
cache: 
 
  directories: 
 
  - "$HOME/.cache" 
 
 
 
deploy: 
 
  provider: script 
 
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy" 
 
  skip_cleanup: true 
 
  on: 
 
    tags: true 
 
 
 
default_text_charset: 'utf-8' 
 
 
 
notifications: 
 
  email: 
 
    - andreacalifano1996@gmail.com
